### ISSUE TITLE
Rose-Piné Colors are off

### ISSUE THREAD

**Issue by randomn4me** [Misterio77/nix-colors#38]
Hi,

I'm pretty new to nix and I'm unable to fix this problem on my own. I noticed, that the colors for rose-pine are not consistent with the upstream in https://github.com/tinted-theming/base16-schemes/blob/main/rose-pine.yaml
I created a waybar style to test this and got the following colors:

```css
#custom-00 { background: #191724; color: #e0def4; }
#custom-01 { background: #1f1d2e; color: #e0def4; }
#custom-02 { background: #26233a; color: #e0def4; }
#custom-03 { background: #555169; color: #e0def4; }
#custom-04 { background: #6e6a86; color: #e0def4; }
#custom-05 { background: #e0def4; }
#custom-06 { background: #f0f0f3; }
#custom-07 { background: #c5c3ce; }
#custom-08 { background: #e2e1e7; }
#custom-09 { background: #eb6f92; }
#custom-0A { background: #f6c177; }
#custom-0B { background: #ebbcba; }
#custom-0C { background: #31748f; }
#custom-0D { background: #9ccfd8; }
#custom-0E { background: #c4a7e7; }
#custom-0F { background: #e5e5e5; }
```
while upstream of base16-schemes has the following colors

```
base00: "191724"
base01: "1f1d2e"
base02: "26233a"
base03: "6e6a86"
base04: "908caa"
base05: "e0def4"
base06: "e0def4"
base07: "524f67"
base08: "eb6f92"
base09: "f6c177"
base0A: "ebbcba"
base0B: "31748f"
base0C: "9ccfd8"
base0D: "c4a7e7"
base0E: "f6c177"
base0F: "524f67"
```

My guess is, that the used commit is locked in the flake.lock file of this repo, but as I said, I'm pretty new to nix and it is still confusing sometimes. I might create a PR if I am able to understand the problem, but for now I'm just happy to create a working config for my system :peace_symbol: The config, which showcases this issue can be found here https://github.com/randomn4me/nix-flakes/tree/dev with the waybar config placed here https://github.com/randomn4me/nix-flakes/blob/dev/home/phil/features/desktop/common/wayland-wm/waybar.nix

Cheers
